/* eslint-disable */
/// <reference types="@cloudflare/workers-types" />
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareBindings cloudflare-env.d.ts` (hash: 69ef98eea21aa0917b1fb82c63985f9d)
interface __BaseEnv_CloudflareBindings {
	DB: D1Database;
	ASSETS: Fetcher;
	CF_VERSION_METADATA?: WorkerVersionMetadata;
}
declare namespace Cloudflare {
	interface PreviewEnv {
		DB: D1Database;
		ASSETS: Fetcher;
	}
	interface ProductionEnv {
		DB: D1Database;
		ASSETS: Fetcher;
	}
	interface Env extends __BaseEnv_CloudflareBindings {}
}
interface CloudflareBindings extends __BaseEnv_CloudflareBindings {}

declare module "cloudflare:workers" {
	const env: CloudflareBindings & { PUBG_API_KEY?: string }
	export { env }
}
